package avlyakulov.timur.taskTrackerApi.exception;

public class AppExceptionMessage {

    public static final String USER_ALREADY_EXISTS = "User with such login already exists";
    public static final String CRED_NOT_CORRECT = "Login or password isn't correct";
    public static final String TASK_NOT_FOUND = "Task wasn't found id database";
    public static final String URL_NOT_FOUND = "This url isn't found. Please change your url";
}